### PR TITLE
MAYA-123716 - As a user, I'd like my duplicated prim to be on the Display Layer that the source prim was on

### PR DESCRIPTION
**Pull request by vlasovi**
This PR fixes a bug in the original code by introducing a code to properly replace USD prefixes when copying to USD.

### CODE REVIEW

**Review by pierrebai-adsk — CHANGES_REQUESTED** [review]
It is unclear to me why the change make the new prim be on the display layer, but I trust that it works. OTOH, a unit test that demonstrates the old problem and how the change fixes the issue would be welcome.

**Comment by neilh-adsk** [comment]
@vlasovi , can you confirm Pierre's question "It is unclear to me why the change make the new prim be on the display layer," before we merge this change ?

**Review by pierrebai-adsk — APPROVED** [review]

**Comment by vlasovi** [comment]
> @vlasovi , can you confirm Pierre's question "It is unclear to me why the change make the new prim be on the display layer," before we merge this change ?

The old code calculated the wrong UFE path by applying the rename string in the wrong place. The new code fixes this issue by using the full USD prefixes

**Comment by seando-adsk** [comment]
@vlasovi As PierreB suggested could you add a unit test that covers this case?

**Comment by vlasovi** [comment]
> @vlasovi As PierreB suggested could you add a unit test that covers this case?

Yes. A separate Jira ticket was added for that.

**Pull request merged**
