### PR TITLE
Revert "Merge pull request #2548 from dgovil/always_write_colorspace"

### PR DESCRIPTION
**Pull request by JGamache-autodesk**
This reverts commit 9cc177dd9949a2fb07e8f710a6cad8850201351a, reversing
changes made to fe1581b8fa3bb31e417c8b680f26e58f3758ad3e.

### CODE REVIEW

**Comment by dgovil** [comment]
Anything I should be concerned about with this?

**Comment by JGamache-autodesk** [comment]
**This PR will never be merged.** Once the experiment is done, this PR and its associated branch will be deleted.

We are trying to find a regression in our build pipeline. And reverting all recent merges one by one to see if we can get back to a good valid build (and find the first problematic merge).

**Comment by JGamache-autodesk** [comment]
Sorry for the noise...

**Comment by dgovil** [comment]
Oh no worries! I just wanted to make sure I didn't screw something up :-)

**Pull request closed without merging**
