### PR TITLE
MAYA-110596 MAYA-110576 faster point snapping

### PR DESCRIPTION
**Pull request by huidong-chen**
The component level is coarse-grain, causing Maya to produce selection hits with undesired selection levels, i.e. face/edge selection hits, as well as vertex selection hits that are required by point snapping. Switch to the new vertex selection level if available in order to produce vertex selection hits only.

### CODE REVIEW

**Review by williamkrick — APPROVED** [review]

**Comment by HdC-adsk** [comment]
PF fails because the required API is not yet built into the blessed maya cut.

**Comment by HdC-adsk** [comment]
@williamkrick @JGamache-autodesk  The required API change has been backported so I pushed a new commit to update the Maya API version check.

**Comment by HdC-adsk** [comment]
As suggested by Krystian , I included the commit which is to solve another task of the point snapping performance epic in this pull request, in order to make it easier for partners to validate when ready.

I will need more testing before asking William and Jerry to review again.

**Comment by HdC-adsk** [comment]
As commented above, I pushed another commit to this pull request which is to skip creating/updating point snapping items when maya has the new point snapping support. It is now ready for review. Thanks.

**Review by williamkrick — APPROVED** [review]

**Review by JGamache-autodesk — APPROVED** [review]

**Comment by HdC-adsk** [comment]
The pull request should be merged after Maya Preview Release 125 in which we will ship the point snapping support.

**Comment by HdC-adsk** [comment]
Aside from new commits to pass clang_format_linter and pre-flight, I also make a new commit to keep selection update enabled, which will reduce frequency of calling `GetSelectionKind()`, `GetPointInstancesPickMode()` and `GetListAdjustment()`, from once per selection hit to once per selection pass.

**Comment by HdC-adsk** [comment]
@JGamache-autodesk Can you please review commit a106699?

**Review by JGamache-autodesk — APPROVED** [review]

**Pull request merged**
