### PR TITLE
fixes for usd < 19.11 compilation (refactoring_sandbox branch)

### PR DESCRIPTION
**Pull request by elrond79**
I made needed to get compilation working for 19.07 for some comparisons I was doing, and AL said they needed 0.19.07 support... so here it is!

This PR is for support against refactoring_sandbox - it depends on https://github.com/Autodesk/maya-usd/pull/213 and https://github.com/Autodesk/maya-usd/pull/215, which should both be merged first

### CODE REVIEW

**Comment by kxl-adsk** [comment]
@elrond79 I believe this should be going into refactoring_sandbox NOT dev branch?

**Comment by elrond79** [comment]
Yes, my mistake!

**Comment by kxl-adsk** [comment]
Perfect. Dependent PRs went already in. It should be ok to merge or you are still working on it? (remove do-not-merge-yet flag if it's ready to go).

**Comment by elrond79** [comment]
Yup, looks good to go!

**Pull request merged**
