### PR TITLE
changes / fixes for rpaths handling

### PR DESCRIPTION
**Pull request by elrond79**
fixes several rpath problems in AL plugin
standardizes usage of CMAKE_INSTALL_PREFIX, and INSTALL_DIR_SUFFIX

### CODE REVIEW

**Comment by HamedSabri-adsk** [comment]
@elrond79 
I merged all your branches ( pr/al/testPathFixes, pr/al/use_buildTempPath, pr/core/rpath_fixes ) into a temporary local branch. Everything builds Ok but some tests still fails and  I also get the unhappy dinosaur!

```
➜  al ctest    
Test project /home/sabrih/Desktop/workspace2/build/RelWithDebInfo/plugin/al
    Start 1: AL_MayaUtilsTests
1/8 Test #1: AL_MayaUtilsTests ................   Passed    6.60 sec
    Start 2: GTest:AL_USDTransactionTests
2/8 Test #2: GTest:AL_USDTransactionTests .....   Passed    0.09 sec
    Start 3: Python:AL_USDTransactionTests
3/8 Test #3: Python:AL_USDTransactionTests ....   Passed    0.29 sec
    Start 4: TestAL_USDMaya
4/8 Test #4: TestAL_USDMaya ...................***Failed   18.72 sec
    Start 5: TestUSDMayaPython
5/8 Test #5: TestUSDMayaPython ................***Failed    7.93 sec
    Start 6: TestAdditionalSchemas
6/8 Test #6: TestAdditionalSchemas ............   Passed    0.12 sec
    Start 7: TestAdditionalTranslators
7/8 Test #7: TestAdditionalTranslators ........***Failed    7.20 sec
    Start 8: TestPxrUsdTranslators
8/8 Test #8: TestPxrUsdTranslators ............***Failed    6.81 sec

50% tests passed, 4 tests failed out of 8

Total Test time (real) =  47.75 sec

The following tests FAILED:
          4 - TestAL_USDMaya (Failed)
          5 - TestUSDMayaPython (Failed)
          7 - TestAdditionalTranslators (Failed)
          8 - TestPxrUsdTranslators (Failed)
Errors while running CTest
```

```
➜  al ctest -R TestAL_USDMaya -VV
4: [----------] 2 tests from translators_PythonBindings
4: [ RUN      ] translators_PythonBindings.import
4: Error: file: /home/sabrih/Desktop/luma/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/run_mayaplugin_tests.mel line 3: ImportError: file /home/sabrih/Desktop/workspace2/install/RelWithDebInfo/plugin/al/lib/python/AL/usdmaya/__init__.py line 18: No module named pxr
4: /home/sabrih/Desktop/luma/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_PythonBindings.cpp:49: Failure
4: Value of: status
4:   Actual: false
4: Expected: true
4: [  FAILED  ] translators_PythonBindings.import (4 ms)
4: [ RUN      ] translators_PythonBindings.unknownType
4: Error: file: /home/sabrih/Desktop/luma/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/run_mayaplugin_tests.mel line 3: ImportError: file /home/sabrih/Desktop/workspace2/install/RelWithDebInfo/plugin/al/lib/python/AL/usdmaya/__init__.py line 18: No module named pxr
4: /home/sabrih/Desktop/luma/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_PythonBindings.cpp:81: Failure
4: Value of: status
4:   Actual: false
4: Expected: true
4: [  FAILED  ] translators_PythonBindings.unknownType (1 ms)
4: [----------] 2 tests from translators_PythonBindings (5 ms total)
4: 
4: [----------] 2 tests from usdmaya_AttributeType
4: [ RUN      ] usdmaya_AttributeType.enums
4: [       OK ] usdmaya_AttributeType.enums (0 ms)
4: [ RUN      ] usdmaya_AttributeType.attributes
4: [       OK ] usdmaya_AttributeType.attributes (2 ms)
4: [----------] 2 tests from usdmaya_AttributeType (2 ms total)
4: 
4: [----------] Global test environment tear-down
4: [==========] 276 tests from 47 test suites ran. (11962 ms total)
4: [  PASSED  ] 274 tests.
4: [  FAILED  ] 2 tests, listed below:
4: [  FAILED  ] translators_PythonBindings.import
4: [  FAILED  ] translators_PythonBindings.unknownType
4: 
4:  2 FAILED TESTS
4:                __
4:               /x_)
4:      _/\/\/\_/ /
4:    _|         /
4:  _|  (  | (  |
4: /__.-'|_|--|_|
4: 
1/1 Test #4: TestAL_USDMaya ...................***Failed   19.48 sec
```
```
➜  al ctest -R TestPxrUsdTranslators -VV
8: ======================================================================
8: ERROR: setUpClass (__main__.TestTranslator)
8: ----------------------------------------------------------------------
8: Traceback (most recent call last):
8:   File "/home/sabrih/Desktop/luma/maya-usd/plugin/al/translators/pxrUsdTranslators/tests/testPxrTranslators.py", line 13, in setUpClass
8:     mc.loadPlugin('pxrUsd')
8: RuntimeError: Plug-in, "pxrUsd", was not found on MAYA_PLUG_IN_PATH.
8: 
8: 
8: ----------------------------------------------------------------------
8: Ran 0 tests in 0.015s
8: 
8: FAILED (errors=1)
1/1 Test #8: TestPxrUsdTranslators ............***Failed    6.84 sec
```
```
➜  al ctest -R TestAdditionalTranslators -VV

7: Test command: /home/sabrih/Desktop/luma/maya-usd/plugin/al/translators/tests/testTranslators.sh "/home/sabrih/Desktop/workspace2/install/RelWithDebInfo/plugin/al" "/home/sabrih/Desktop/build_usd/lib" "/home/sabrih/Desktop/luma/maya-usd/plugin/al/translators/tests"
7: Test timeout computed to be: 10000000
7: Result: untitled
7: Error: line 1: AttributeError: file /home/sabrih/Desktop/workspace2/install/RelWithDebInfo/plugin/al/lib/python/AL/usdmaya/__init__.py line 17: 'NoneType' object has no attribute '__MFB_FULL_PACKAGE_NAME'
1/1 Test #7: TestAdditionalTranslators ........***Failed    7.39 sec

0% tests passed, 1 tests failed out of 1
```
```
➜  al ctest -R TestUSDMayaPython -VV        
5: ======================================================================
5: ERROR: test_getMayaPathFromUsdPrim_failure (__main__.TestProxyShapeGetMayaPathFromUsdPrim)
5: Query a proxy with an invalid prim.
5: ----------------------------------------------------------------------
5: Traceback (most recent call last):
5:   File "/home/sabrih/Desktop/luma/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/py/testProxyShape.py", line 150, in setUp
5:     self._stageA.proxy = AL.usdmaya.ProxyShape.getByName(self._stageA.proxyName)
5: AttributeError: 'module' object has no attribute 'usdmaya'
5: 
5: ======================================================================
5: ERROR: test_getMayaPathFromUsdPrim_primStageMismatch (__main__.TestProxyShapeGetMayaPathFromUsdPrim)
5: Query a proxy with a prim from a different Usd stage.
5: ----------------------------------------------------------------------
5: Traceback (most recent call last):
5:   File "/home/sabrih/Desktop/luma/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/py/testProxyShape.py", line 150, in setUp
5:     self._stageA.proxy = AL.usdmaya.ProxyShape.getByName(self._stageA.proxyName)
5: AttributeError: 'module' object has no attribute 'usdmaya'
5: 
5: ======================================================================
5: ERROR: test_getMayaPathFromUsdPrim_staticImport (__main__.TestProxyShapeGetMayaPathFromUsdPrim)
5: Force import a prim.
5: ----------------------------------------------------------------------
5: Traceback (most recent call last):
5:   File "/home/sabrih/Desktop/luma/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/py/testProxyShape.py", line 150, in setUp
5:     self._stageA.proxy = AL.usdmaya.ProxyShape.getByName(self._stageA.proxyName)
5: AttributeError: 'module' object has no attribute 'usdmaya'
5: 
5: ======================================================================
5: ERROR: test_getMayaPathFromUsdPrim_success (__main__.TestProxyShapeGetMayaPathFromUsdPrim)
5: Maya scenes can contain multiple proxies. Query each proxy and test they return the correct Maya nodes.
5: ----------------------------------------------------------------------
5: Traceback (most recent call last):
5:   File "/home/sabrih/Desktop/luma/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/py/testProxyShape.py", line 150, in setUp
5:     self._stageA.proxy = AL.usdmaya.ProxyShape.getByName(self._stageA.proxyName)
5: AttributeError: 'module' object has no attribute 'usdmaya'
5: 
5: ======================================================================
5: ERROR: test_getMayaPathFromUsdPrim_unselected (__main__.TestProxyShapeGetMayaPathFromUsdPrim)
5: Query a proxy with a valid prim who's Maya node has not been translated (unselected).
5: ----------------------------------------------------------------------
5: Traceback (most recent call last):
5:   File "/home/sabrih/Desktop/luma/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/py/testProxyShape.py", line 150, in setUp
5:     self._stageA.proxy = AL.usdmaya.ProxyShape.getByName(self._stageA.proxyName)
5: AttributeError: 'module' object has no attribute 'usdmaya'
5: 
5: ----------------------------------------------------------------------
5: Ran 7 tests in 0.168s
5: 
5: FAILED (errors=5, skipped=2)
5: Error: line 1: RuntimeError: file /home/sabrih/Desktop/luma/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/py/testProxyShape.py line 303: Scene modified.  Use file -s to save or quit -f to quit without saving.
1/1 Test #5: TestUSDMayaPython ................***Failed    7.97 sec

0% tests passed, 1 tests failed out of 1
```

**Comment by elrond79** [comment]
Not sure how to help - looks like some plugin path / python path issues.  Are there any tests that used to work, but now fail with this fix?  Or vice-versa?

**Comment by kxl-adsk** [comment]
@elrond79 are these tests failing for you too?

> The following tests FAILED:
          4 - TestAL_USDMaya (Failed)
          5 - TestUSDMayaPython (Failed)
          7 - TestAdditionalTranslators (Failed)
          8 - TestPxrUsdTranslators (Failed)

@murphyeoin I wonder if they should be passing?

**Comment by elrond79** [comment]
All tests pass for me.

**Comment by kxl-adsk** [comment]
Is this with or without using the build script from this repository?

**Comment by elrond79** [comment]
Without.  We invoke cmake directly, as well as do some basic env var
setup... which might explain the different results.

**Comment by kxl-adsk** [comment]
@murphyeoin can you please review this change before we merge it?

**Comment by murphyeoin** [comment]
Hi @elrond79 sorry about delay on this. Now that I have the vanilla build and tests up and running I will try this one asap tomorrow

**Comment by kxl-adsk** [comment]
@elrond79 Please resolve merge conflicts.

**Comment by elrond79** [comment]
Ok, pushed a rebase which fixes the merge conflicts...

**Pull request merged**
