### PR TITLE
Use Hydra fix for Geom subset mat Id paths

### PR DESCRIPTION
**Pull request by dj-mcg**
Geom Subsets accessed via UsdImagingDelegate::GetMeshTopology now have
correctly prefixed index paths for id and materialId, so callsites no
longer have to perform this conversion

### CODE REVIEW

**Review by vlasovi — APPROVED** [review]
Looks good. Thanks for the improvement.

**Comment by seando-adsk** [comment]
@dj-mcg There is a merge conflict that needs to be fixed before I can merge.

**Comment by dj-mcg** [comment]
Thanks @seando-adsk - should be resolved now

**Comment by seando-adsk** [comment]
@dj-mcg The clang format step failed now (after you fixed the merge conflict). Can you please have a look at that.

**Comment by dj-mcg** [comment]
I screwed this branch up and I think it'll just be easier to re-apply the changes in a new branch. Incoming

**Pull request closed without merging**
