### PR TITLE
Export all inline functions from the proxyshape, and remove the WANT_UFE_BUILD conditional compiles from the headers

### PR DESCRIPTION
**Pull request by csyshing**
Description
------------
This PR comes down to some memory corruption within the proxy shape class.
The WANT_UFE_BUILD define might not be correctly defined within projects that use pointers to the ProxyShape node, which can cause memory misalignments (as can additional variables that are added to the Autodesk base class).
We have removed those issues, and have simply exported all ProxyShape methods rather than using the inline methods.

### CODE REVIEW

**Comment by csyshing** [comment]
Jenkins build failed with this error:
```
     84/202 Test  #70: testVP2RenderDelegatePerInstanceInheritedData ...***Failed   23.34 sec
    MAYA_DEBUG_NO_SAVE_ON_CRASH is set.
    __feature__ could not be imported. This is an unsolved PyInstaller problem.
    ======================================================================
    FAIL: testPerInstanceInheritedDataPartialOverridePxrMtls (__main__.testVP2RenderDelegatePerInstanceInheritedData)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "S:/jenkins/workspace/ecg-mayausd-branch-preflight-2022-python2-pxrusd-min-interactive-windows/ecg-maya-usd/maya-usd/test/lib/mayaUsd/render/vp2RenderDelegate\testVP2RenderDelegatePerInstanceInheritedData.py", line 136, in testPerInstanceInheritedDataPartialOverridePxrMtls
        self._StartTest('inheritedDisplayColor_noPxrMtls')
      File "S:/jenkins/workspace/ecg-mayausd-branch-preflight-2022-python2-pxrusd-min-interactive-windows/ecg-maya-usd/maya-usd/test/lib/mayaUsd/render/vp2RenderDelegate\testVP2RenderDelegatePerInstanceInheritedData.py", line 85, in _StartTest
        self.assertSnapshotClose('%s_unselected.png' % self._testName)
      File "S:/jenkins/workspace/ecg-mayausd-branch-preflight-2022-python2-pxrusd-min-interactive-windows/ecg-maya-usd/maya-usd/test/lib/mayaUsd/render/vp2RenderDelegate\testVP2RenderDelegatePerInstanceInheritedData.py", line 73, in assertSnapshotClose
        return self.assertImagesClose(baselineImage, snapshotImage)
      File "S:\jenkins\workspace\ecg-mayausd-branch-preflight-2022-python2-pxrusd-min-interactive-windows\ecg-maya-usd\maya-usd\test\testUtils\imageUtils.py", line 193, in assertImagesClose
        self.fail(msg)
    AssertionError: Images differed by 0.000315976004599 (max allowed: 0.0001):
      S:\jenkins\workspace\ecg-mayausd-branch-preflight-2022-python2-pxrusd-min-interactive-windows\ecg-maya-usd\maya-usd\test\lib\mayaUsd\render\vp2RenderDelegate\VP2RenderDelegatePerInstanceInheritedDataTest\baseline\inheritedDisplayColor_noPxrMtls_unselected.png
      W:\build\RelWithDebInfo\test\lib\mayaUsd\render\vp2RenderDelegate\testVP2RenderDelegatePerInstanceInheritedDataOutput\inheritedDisplayColor_noPxrMtls_unselected.png
    
    ----------------------------------------------------------------------

I don't think it's caused by this PR?

**Comment by seando-adsk** [comment]
@csyshing Is there someone who can code review this PR?

**Comment by csyshing** [comment]
@seando-adsk , the same as #1851, it has been reviewed internally in Animal Logic, maybe @kxl-adsk could do the review?

**Review by kxl-adsk — DISMISSED** [review]
I must admit that I don't fully understand how inline functions can cause memory misalignment. Given that you are fine with the potential performance impact of the change on AL proxy shape, I'm approving this change.

**Review by kxl-adsk — APPROVED** [review]

**Pull request merged**
