### PR TITLE
Merge internal refactoring sandbox

### PR DESCRIPTION
**Pull request by kxl-adsk**

### CODE REVIEW

**Comment by BigRoy** [comment]
Sorry for dropping the question here, but I noticed [these AE templates for UFE](https://github.com/Autodesk/maya-usd/blob/7a115294dfe7db383568f872addad0c8607d05b8/lib/ae/base/ae_template.py) popping up and hidden behind a `v2` for UFE? Should that work with any Maya version? Or is that Maya 2020 only?

**Comment by kxl-adsk** [comment]
We will be bringing these changes to the dev branch...and will work with the upcoming beta release. Can't be any more precise than this since we are not allowed to talk about dates in public.

**Comment by BigRoy** [comment]
Ah, sure. It's not about dates. I was just wondering whether I would be able to test these features against Maya 2019 too.

I tried compiling against Maya 2019.2 with it enabled `--build-args=-DCMAKE_UFE_V2_FEATURES_AVAILABLE=True` but ran into some issues:
```
d:\dev\usd\maya-usd\lib\ufe\UsdAttribute.h(20): fatal error C1083: Cannot open include file: 'ufe/attribute.h': No such file or directory (compiling source file D:\dev\usd\maya-usd\lib\ufe\UsdAttribute.cpp) [D:\git_pipeline\rez-packages\maya-usd\build\platform-windows\arch==AMD64\maya-usd\lib\mayaUsd.vcxproj]
D:\dev\usd\maya-usd\lib\ufe\UsdUndoCreateGroupCommand.cpp(75): error C2039: 'createGroup': is not a member of 'Ufe_v1::Hierarchy' [D:\git_pipeline\rez-packages\maya-usd\build\platform-windows\arch==AMD64\maya-usd\lib\mayaUsd.vcxproj]
  C:\Users\Roy\packages\maya_devkit\2019.2\platform-windows\devkitBase\devkit\ufe\include\ufe/hierarchy.h(63): note: see declaration of 'Ufe_v1::Hierarchy'
d:\dev\usd\maya-usd\lib\ufe\UsdAttribute.h(20): fatal error C1083: Cannot open include file: 'ufe/attribute.h': No such file or directory (compiling source file D:\dev\usd\maya-usd\lib\ufe\UsdAttributes.cpp) [D:\git_pipeline\rez-packages\maya-usd\build\platform-windows\arch==AMD64\maya-usd\lib\mayaUsd.vcxproj]
d:\dev\usd\maya-usd\lib\ufe\UsdAttribute.h(20): fatal error C1083: Cannot open include file: 'ufe/attribute.h': No such file or directory (compiling source file D:\dev\usd\maya-usd\lib\ufe\UsdAttributesHandler.cpp) [D:\git_pipeline\rez-packages\maya-usd\build\platform-windows\arch==AMD64\maya-usd\lib\mayaUsd.vcxproj]
```

Log: 
[build_log.txt](https://github.com/Autodesk/maya-usd/files/3894226/build_log.txt)

Should I be able to compile this with success?

**Comment by kxl-adsk** [comment]
No, Maya 2019 has UFE v1.0.

KxL

On Nov 26, 2019, at 17:13, Roy Nieterau <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, sure. It's not about dates. I was just wondering whether I would be able to test these features against Maya 2019 too.

I tried compiling against Maya 2019.2 with it enabled --build-args=-DCMAKE_UFE_V2_FEATURES_AVAILABLE=True but ran into some issues:

d:\dev\usd\maya-usd\lib\ufe\UsdAttribute.h(20): fatal error C1083: Cannot open include file: 'ufe/attribute.h': No such file or directory (compiling source file D:\dev\usd\maya-usd\lib\ufe\UsdAttribute.cpp) [D:\git_pipeline\rez-packages\maya-usd\build\platform-windows\arch==AMD64\maya-usd\lib\mayaUsd.vcxproj]
D:\dev\usd\maya-usd\lib\ufe\UsdUndoCreateGroupCommand.cpp(75): error C2039: 'createGroup': is not a member of 'Ufe_v1::Hierarchy' [D:\git_pipeline\rez-packages\maya-usd\build\platform-windows\arch==AMD64\maya-usd\lib\mayaUsd.vcxproj]
  C:\Users\Roy\packages\maya_devkit\2019.2\platform-windows\devkitBase\devkit\ufe\include\ufe/hierarchy.h(63): note: see declaration of 'Ufe_v1::Hierarchy'
d:\dev\usd\maya-usd\lib\ufe\UsdAttribute.h(20): fatal error C1083: Cannot open include file: 'ufe/attribute.h': No such file or directory (compiling source file D:\dev\usd\maya-usd\lib\ufe\UsdAttributes.cpp) [D:\git_pipeline\rez-packages\maya-usd\build\platform-windows\arch==AMD64\maya-usd\lib\mayaUsd.vcxproj]
d:\dev\usd\maya-usd\lib\ufe\UsdAttribute.h(20): fatal error C1083: Cannot open include file: 'ufe/attribute.h': No such file or directory (compiling source file D:\dev\usd\maya-usd\lib\ufe\UsdAttributesHandler.cpp) [D:\git_pipeline\rez-packages\maya-usd\build\platform-windows\arch==AMD64\maya-usd\lib\mayaUsd.vcxproj]


Log:
build_log.txt<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Autodesk_maya-2Dusd_files_3894226_build-5Flog.txt&d=DwMCaQ&c=76Q6Tcqc-t2x0ciWn7KFdCiqt6IQ7a_IF9uzNzd_2pA&r=zwnvYcOOa_pby2f4J79l0POSwDXNSzzIkZ1_rpKlHUk&m=xEqeW7tDAtKhq5Nrkj8zTSR0UbzhreDVPPUzmngccWg&s=fiHYSZ-KNZsdPynu0e875AatdxyDboYm_MN8aQeern0&e=>

Should I be able to compile this with success?

**Pull request merged**
