### PR TITLE
Fix PXR_PATCH_VERSION!

### PR DESCRIPTION
**Pull request by HamedSabri-adsk**
set patch number to 5.

### CODE REVIEW

**Comment by HamedSabri-adsk** [comment]
Hey Matt, exactly I was wondering too since nobody uses this. 

I will nuke it :)

**Comment by HamedSabri-adsk** [comment]
@mattyjams  see 46b45653af63e10aac1171d33263722f114da7c4

**Comment by kxl-adsk** [comment]
Great, I'm happy to see it

**Comment by HamedSabri-adsk** [comment]
> 
> 
> Please fix compilation errors (all platforms are failing):
> see https://github.com/Autodesk/maya-usd/blob/dev/plugin/pxr/cmake/macros/Private.cmake#L16

Should be fixed in bb84d2caae646bd073c310f08816663a63934ea8

**Pull request merged**
