### PR TITLE
[pxr] get tests building / working for pixar plugin

### PR DESCRIPTION
**Pull request by elrond79**
This contains changes necessary to get the pixar tests building / running in the dev branch.

Note that some changes here could potentially affect things other than tests (ie, there are some rpath changes I needed to get tests to run). so having someone else verify that everything still works for them would be good!

### CODE REVIEW

**Comment by HamedSabri-adsk** [comment]
@elrond79  We have already started the work on getting the unit tests working on all 3 platforms in refactoring_sandbox including fixes for rpaths, etc...  We haven't merged the changes yet into dev.

**Comment by kxl-adsk** [comment]
In fact, quite a lot of this work is included in https://github.com/Autodesk/maya-usd/pull/91. @elrond79 have a look at this PR.

**Comment by elrond79** [comment]
Yes, but we want tests working BEFORE we merge in big changes.  For two reasons:

1) We're planning to make the current dev (before merging in big changes) become the new master.  If we don't fix tests first, the "master" branch - the one that's supposed to be stable, and we want people to use in production - won't have working tests. This is unacceptable for a production environment.

2) We want a baseline before we merge in big changes.  That way, when tests fail after, we know it's a breaking change.

I'm fine if we want to modify this to be more in line with what's coming in #91, etc... (though I did make some attempt to mirror what's coming - ie, I used the same "BUILD_TESTS" cmake var you folks introduced)... however, I definitely think we need to get tests working before bringing in the big changes.

**Comment by elrond79** [comment]
Dropping this PR, as all the fixes here have been addressed in other branches / PRs!

**Pull request closed without merging**
