### PR TITLE
Replacing direct use of 'python' executable with variable.

### PR DESCRIPTION
**Pull request by seando-adsk**

### CODE REVIEW

**Comment by kxl-adsk** [comment]
@murphyeoin can you please review this change?

**Comment by murphyeoin** [comment]
Hi @seando-adsk code itself looks perfect. Where is the variable going to be defined?

**Comment by seando-adsk** [comment]
@murphyeoin It gets defined by FindPythonInterp.cmake which is called here: https://github.com/Autodesk/maya-usd/blob/dev/cmake/python.cmake#L59

**Comment by seando-adsk** [comment]
Note: I had previously made this same type of change a while ago. I guess some new instances of 'python' crept back in.

**Pull request merged**
