### PR TITLE
LOOKDEVX-2324 - Export MaterialX path for extra nodes

### PR DESCRIPTION
**Pull request by JGamache-autodesk**
Allow 3rd party renderers to see MayaUSD MaterialX library and render the nodes.

### CODE REVIEW

**Comment by JGamache-autodesk** [comment]
This allows Arnold to "see" the NodeGraph implementations of nodes like `MayaND_fileTexture_*`, `MayaND_place2dTexture_vector2`, `LdkND_ColorCorrect_color4` and render them correctly.

**Review by feldstj — APPROVED** [review]

**Review by seando-adsk — COMMENTED** [review]
Is this variable need when running the unit tests? If so it needs to be added to test.cmake as we don't use the .mod file when running tests.

**Comment by JGamache-autodesk** [comment]
No, only used by third party renderers (Arnold, VRay, PRMan maybe). So is not used in unit tests. 

Test failure on Linux is one of the usual: testVP2RenderDelegateDisplayLayers

**Comment by JGamache-autodesk** [comment]
@seando-adsk Ready for merge (preflight failure was a random one).

**Pull request merged**
