### PR TITLE
Added namespace section to coding guidelines.

### PR DESCRIPTION
**Pull request by ppt-adsk**

### CODE REVIEW

**Review by HamedSabri-adsk — CHANGES_REQUESTED** [review]
Thanks Pierre. Looking good. 

One small thing though, having "PXR_NAMESPACE_USING_DIRECTIVE" inside a function definition can be confusing. Not only that, there could be many instances of these macros in the same cpp file and having that macro before each one could make a lot of noise.

I would vote to put the directive outside of the function definition and call it just once. 

```
// this directive is needed for Pixar macros, which are not namespaced
PXR_NAMESPACE_USING_DIRECTIVE

inline PXR_NS::UsdPrim prim() const
{
    TF_AXIOM(fItem != nullptr);
    return fItem->prim();
}
```

**Comment by ppt-adsk** [comment]
> 
> 
> Thanks Pierre. Looking good.
> 
> One small thing though, having "PXR_NAMESPACE_USING_DIRECTIVE" inside a function definition can be confusing. Not only that, there could be many instances of these macros in the same cpp file and having that macro before each one could make a lot of noise.
> 
> I would vote to put the directive outside of the function definition and call it just once.
> 
> ```
> // this directive is needed for Pixar macros, which are not namespaced
> PXR_NAMESPACE_USING_DIRECTIVE
> 
> inline PXR_NS::UsdPrim prim() const
> {
>     TF_AXIOM(fItem != nullptr);
>     return fItem->prim();
> }
> ```

This is in a .h file, so you can't...  Let me know if there's any way for me to make the explanation clearer.

**Review by HamedSabri-adsk — APPROVED** [review]
Got it!! You clearly say "In header files".  Looking good.

**Review by kxl-adsk — APPROVED** [review]

**Review by dj-mcg — APPROVED** [review]
Looks good to me, thanks Pierre!

**Review by pmolodo — APPROVED** [review]
Sounds good.  Only suggestion I might have would be regarding formatting - might help (for instance, with Hamed's confusion about .h vs .cpp) to have separate sections, and clearly make required vs recommended.  ie, something like:

```

### Namespaces

#### In header files (e.g. .h)

* **Required:** to use fully qualified namespace names. Global scope using directives are not allowed.  Inline code can use using directives in implementations, within a scope, when there is no other choice (e.g. when using macros, which are not namespaced).

    ```cpp
    // In aFile.h
    inline PXR_NS::UsdPrim prim() const
    {
        PXR_NAMESPACE_USING_DIRECTIVE
        TF_AXIOM(fItem != nullptr);
        return fItem->prim();
    }
    ```

#### In implementation files (e.g. .cpp)

* **Recommended:** to use fully qualified namespace names, unless clarity or readability is degraded by use of explicit namespaces, in which case a using directive is acceptable.
* **Recommended:** to use the existing namespace style, and not make gratuitous changes: if the file is using explicit namespaces, new code should follow this style, unless the changes are so significant that clarity or readability is degraded.  If the file has one or more using directives, new code should follow this style.
```

I'm not wedded to that, though, so I'm also happy to accept this as is.

**Comment by ppt-adsk** [comment]
Two days have gone by, assuming that no further feedback is forthcoming.  Went with Paul's suggestion, ready for merge.

**Pull request merged**
