### PR TITLE
replace use of auto with full type name when getting Ufe::HierarchyHandler::Ptr

### PR DESCRIPTION
**Pull request by mattyjams**
This resolves a template deduction/substitution compilation error encountered
when building with gcc 4.8.3 on Linux.

### CODE REVIEW

**Comment by ppt-adsk** [comment]
Hey Matt, UFE is Maya 2019 and above, and the compiler requirement for Maya 2019 is gcc 6.3.1, so pretty sure your 4.8.3 compiler shouldn't be hitting these lines of code.

**Comment by mattyjams** [comment]
Hmm... This is definitely breaking our Maya 2019 builds. We're working on moving to a more recent VFX platform and compiler, but we're not quite ready to move off of gcc 4.8.3 yet. All the rest of our public and internal code still successfully builds and runs with that compiler though.

It looks like the only thing that gates this code is `WANT_UFE_BUILD`, which will be enabled if a `MAYA_DEVKIT_LOCATION` is provided. I'm doing that by passing a path to the --devkit-location option of build.py.

I can understand if UFE isn't officially supported with gcc versions earlier than 6.3.1, and at least in the very near term we're not actually depending on that functionality. I'd like to avoid having to disable UFE in our builds though. My main concern is that as core USD changes, we (Pixar) would like to help make sure that everything in the maya-usd repo still builds, and us having to disable the UFE build will leave out a chunk of code that someone else might find to be broken by some core USD API change.

**Comment by ppt-adsk** [comment]
O.K., we appreciate the intent of providing coverage for UFE code, and we get that moving to a newer compiler is usually a drawn-out process.  Since this is something that unblocks you, it's in.  For your reference (but you probably know this already), here are the docs for the Maya 2019 compiler requirements:
https://help.autodesk.com/view/MAYAUL/2019/ENU/?guid=Maya_SDK_MERGED_Setting_up_your_build_Linux_environment_html
We at Autodesk will not be validating UFE against gcc 4.8.3.

**Comment by mattyjams** [comment]
Great, thanks very much! And definitely understood. I caught up with our build team and it sounds like the goal is to get our developers onto gcc 6.3.1 before the end of the year, so hopefully we shouldn't be on this unsupported configuration for too much longer.

Thanks again!

**Pull request merged**
