### PR TITLE
Merge latest from Pixar dev branch into maya-usd dev branch

### PR DESCRIPTION
**Pull request by mattyjams**
This merges commits from the Pixar USD repo dev branch as of 1d08054341653e46cbb7120f65cc97c43133775d into the maya-usd dev branch.

Note that this is not yet the final release of 19.11. I'll setup another merge when that goes out.

### CODE REVIEW

**Comment by BigRoy** [comment]
Note that USD 19.11 release is 'scheduled' for October 18th, this Friday. See [here](https://groups.google.com/forum/#!topic/usd-interest/_TbFL7UcpOE). Not saying this PR and it's good to prepare reviewal for the changes so far. 👍 Just stating it for those who are unaware that it'll likely find a full release soon.

**Comment by kxl-adsk** [comment]
Can you as well update https://github.com/Autodesk/maya-usd/blob/dev/doc/DEVELOPER.md table? You can remove master, dev and refactoring_sandbox rows and just have one row. It wasn't a good idea to have one branch provide info about other branches - it's too easy for it to go out of sync.

Also, when I diff changes since the last merge, I see 14 files changed in the Maya folder but this PR modifies 20 files. I didn't have time to compare it yet, but maybe you could provide an explanation for it?

**Comment by mattyjams** [comment]
I just added 8febcdd that updates DEVELOPER.md.

I assume the diff you're looking at is something like this?:
https://github.com/PixarAnimationStudios/USD/compare/b85ddac2...1d08054

There are 15 files in this PR in the Maya area. The one additional one that might not be represented in that diff is the addition of the prim.h include in stageNode.cpp. That's going to be required by a yet-to-be-pushed to dev change to core USD, so I snuck it in now so that we (Pixar) can build the dev branch against our slightly ahead version of USD. You caught me. :)

Other than the Maya files, there are four CMake-related files, the LICENSE.txt, and now the DEVELOPER.md for a total of 21 changed files.

**Comment by kxl-adsk** [comment]
LGTM. Thank you!

**Pull request merged**
