### PR TITLE
Removing code blocks for USD 19.07

### PR DESCRIPTION
**Pull request by kxl-adsk**
With recent support added for USD 20.08, we are dropping support for fairly old 19.07.

### CODE REVIEW

**Comment by kxl-adsk** [comment]
@HamedSabri-adsk what's the string that you were looking for? I examined a few files that you have listed, but then do not have code conditionally compiled for `19.07`. Is it possible that you made a mistake and looked for `19.11`?

**Comment by HamedSabri-adsk** [comment]
@kxl-adsk right, I explicitly searched for both 19.07 and 19.11. 

The places that I mentioned above are where we have 19.11.  If I am not mistaking, there are places in those files that we still implicitly use code from earlier version of 19.11.

e.g lib/mayaUsd/render/mayaToHydra/renderOverride.cpp

```
#if USD_VERSION_NUM >= 1911
#include <pxr/imaging/hd/rendererPluginRegistry.h>
#else
#include <pxr/imaging/hdx/rendererPluginRegistry.h>
PXR_NAMESPACE_OPEN_SCOPE
using HdRendererPluginRegistry = HdxRendererPluginRegistry;
PXR_NAMESPACE_CLOSE_SCOPE
#endif
```
The else condition above happens to older version of 19.11.  I was under the impression that these needs to be also removed?

**Comment by kxl-adsk** [comment]
Good catch...my weekend brain missed that!

**Comment by kxl-adsk** [comment]
@HamedSabri-adsk see https://github.com/Autodesk/maya-usd/pull/734/commits/4a3876851c20502b3e8664c1f7917708d63f9f88

**Comment by HamedSabri-adsk** [comment]
@kxl-adsk  Thank you for the changes. 

There are couple of places in lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp that can be cleaned up :

**line 880 - 888**
**line 990 - 1006**
**line 1266 -1276**

**Comment by kxl-adsk** [comment]
@HamedSabri-adsk what exactly you propose to remove at these lines? For example
```
#if USD_VERSION_NUM > 1911
                "        HIT:\n"
                "            delegateId      : %s\n"
                "            objectId        : %s\n"
                "            normalizedDepth : %f\n",
                hit.delegateId.GetText(),
                hit.objectId.GetText(),
                hit.normalizedDepth);
#else
                "        HIT:\n"
                "            delegateId: %s\n"
                "            objectId  : %s\n"
                "            ndcDepth  : %f\n",
                hit.delegateId.GetText(),
                hit.objectId.GetText(),
                hit.ndcDepth);
#endif
```

Else case is required for 19.11 version.

**Comment by HamedSabri-adsk** [comment]
@kxl-adsk  the else condition applies to older version of 19.11

https://github.com/Autodesk/maya-usd/blob/4a3876851c20502b3e8664c1f7917708d63f9f88/lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp#L888-L896

**Pull request merged**
