### PR TITLE
MAYA-114979 - Validate normal maps for correctness

### PR DESCRIPTION
**Pull request by JGamache-autodesk**
Also check monochromatic inputs.

Connecting a file texture node interactively or by script will
automatically set the color attributes on the file node according to the
destination of the connection.

@dgovil : Added an env var for automatic fixups on load.

Second PR for issue #1834

### CODE REVIEW

**Comment by dgovil** [comment]
Thanks for tagging me to keep me in the loop. 

I like the setup you've created for this. That env var will be very useful.

**Review by boudrey — APPROVED** [review]
LGTM

**Comment by dgovil** [comment]
@JGamache-autodesk One point that had come up internally is that perhaps this should respect the `ignoreColorSpaceFileRules` setting in Maya to allow for manual control in those scenarios.

We can put in a PR if you like, but just wanted to get your thoughts first?

**Comment by JGamache-autodesk** [comment]
@dgovil setting `ignoreColorSpaceFileRules` makes a lot of sense, otherwise a change at the global level will flip the settings. If you have a PR ready please post it. Thanks!

**Comment by dgovil** [comment]
Cool, I'll prepare a PR

**Pull request merged**
