### PR TITLE
Enable proxyAccessor in AL_USDMaya

### PR DESCRIPTION
**Pull request by jossh-h**
Enable proxyAccessor for the AL_USDMaya plugin

### CODE REVIEW

**Comment by fabal** [comment]
The build errors don't seem related to these changes, let us know if we missed something.

**Comment by seando-adsk** [comment]
@fabal / @jossh-h - Can you please verify that "jossh-h" is listed in your CLA for contributions. I don't see that user, but maybe I'm just missing the username -> real name. Thanks, Sean

**Comment by jossh-h** [comment]
> @fabal / @jossh-h - Can you please verify that "jossh-h" is listed in your CLA for contributions. I don't see that user, but maybe I'm just missing the username -> real name. Thanks, Sean

Hi @seando-adsk , If im not listed there ( Josh Henare ) then I can check with the team about getting me added. Thanks!, Josh

**Comment by seando-adsk** [comment]
Added the "do not merge yet" label until Josh is added to the CLA.

**Pull request merged**
