### PR TITLE
[pxr] fix for building with PXR_VALIDATE_GENERATED_CODE

### PR DESCRIPTION
**Pull request by elrond79**
Handy when doing releases...

### CODE REVIEW

**Comment by kxl-adsk** [comment]
What's the reasoning for opening this PR for master?

**Comment by elrond79** [comment]
Because it's pertinent to master's purpose (stable release builds), and because it's easy to merge from master to dev, but we don't want to merge the other way right now.

Having said that, it's also not crucial, so if you'd prefer it be against dev, I can change the target.

**Comment by kxl-adsk** [comment]
Please change to be against dev.

**Comment by elrond79** [comment]
Done.

**Pull request merged**
