### PR TITLE
October PRs from AnimalLogic

### PR DESCRIPTION
**Pull request by murphyeoin**
I've squashed all of our internal PRs into a single PR, with a commit per PR - hope this is the last time I need to do this!
@kxl-adsk we have a PR to add the missing licence headers, but it depends on this one

### CODE REVIEW

**Comment by kxl-adsk** [comment]
@murphyeoin Can you please resolve merge conflicts?

**Comment by murphyeoin** [comment]
Hi @kxl-adsk yes hoping to get to it over the next few days

**Comment by murphyeoin** [comment]
Done - sorry for the delay

**Comment by kxl-adsk** [comment]
It fails to build on OSX

> /maya-usd/plugin/al/usdmayautils/AL/usdmaya/utils/AnimationTranslator.cpp:262:10: error: no member named 'cerr' in namespace 'std'
    std::cerr << "Unable to initialize common transform attributes for animation test." << std::endl;
    ~~~~~^
1 error generated.

**Comment by kxl-adsk** [comment]
Missing include in AnimationTranslator.cpp -> #include <iostream>

**Comment by murphyeoin** [comment]
HI @kxl-adsk - so it looks like this is more than a simple merge conflict - this PR built fine for us internally when I originally submitted it, but as a huge amount of changes have gone into dev in the meantime, looks like I'll need to revalidate..

**Comment by kxl-adsk** [comment]
We saw this missing include in the past already...it could be only OSX related.

**Comment by ppt-adsk** [comment]
Hey Eoin, there have been include file changes to MStatus.h, which previously was including way too much --- including some iostream stuff, IIRC.  You may want to check on that, to see if it's relevant.

**Comment by kxl-adsk** [comment]
FWIW. This would explain why you don't see any issue with Maya 2019 and beta build is failing.

**Comment by murphyeoin** [comment]
@kxl-adsk @ppt-adsk I have pulled this branch into our newly set up CI system with docker based linux build and tests are passing successfully for me. We're not able to easily run OSX or Windows tests so we'll have to rely on you for these

**Comment by kxl-adsk** [comment]
@murphyeoin weird, there are many commits from dev branch listed in this PR. How did you add the missing include?

**Comment by kxl-adsk** [comment]
hmmm...I think it's a github issue, when I compare your branch with dev, I only see your commits - https://github.com/Autodesk/maya-usd/compare/dev...AnimalLogic:OctoberFeatures2

**Pull request merged**
