### PR TITLE
[util] make MayaNodeNameToSdfPath deal with underworld nodes

### PR DESCRIPTION
**Pull request by elrond79**
This opens the door for exporting / importing imagePlane nodes in the future.

### CODE REVIEW

**Comment by kxl-adsk** [comment]
It's unclear to me what is the problem that this PR is solving? Once that's cleared out, we will need a unit test for it.

**Comment by elrond79** [comment]
Without this change, it will error when it tries to translate underworld nodes, like:

`|foo|myMesh|myMeshShape->|underworldXform`

or, more commonly:

`|foo|myCamera|myCameraShape->|imagePlane1|imagePlaneShape1`

This came out of my maya-to-hydra refactoring, where I was removing the luma-specific code.  The removed code adds support for imagePlanes, but requires a corresponding branch on USD, which we haven't published yet.

This was the only bit that wasn't directly related to image planes - I wasn't sure how common underworld-node use was, outside of image planes, so I thought I'd make the PR.  (I only know of one other case where underworld nodes are created automatically - some sort of nurbs-surface projection node, I think.) If you don't think anyone will care, I can just make it part of our internal (imagePlane-specific) branch, and I'll close this PR.

And yeah, if you think it would be useful, I can absolutely make a unittest for it!

**Comment by kxl-adsk** [comment]
Thank you for the explanation. It makes sense to add and you have a very valid case. Please add a unit test for it.

**Comment by elrond79** [comment]
I couldn't find an easy way to create an import / export error that this would solve, without also adding an ImagePlane translator, so I'm just going to close this PR for now. Will re-open if I come up with a better test case.

**Pull request closed without merging**
