### PR TITLE
Update dev branch to include latest AL develop, and (nearly) latest Pixar dev

### PR DESCRIPTION
**Pull request by elrond79**
Also includes the PR from Autodesk:

https://github.com/LumaPictures/maya-usd/pull/1

...and merges in the latest changes from master

### CODE REVIEW

**Comment by elrond79** [comment]
So, I updated / fixed the "replace_lic.py"  utiltity to deal with with converting these licenses from AL.  To run it, just cd to the root of the repo, then run:

```
python replace_lic.py
```

(with a python-2 interpreter).

I didn't run / commit the results yet, because I wasn't sure if you also wanted to fix the pixar-style modified-apache licenses.

**Comment by HamedSabri-adsk** [comment]
I haven't seen the additional // with the pixar copyright headers. It is AL only.

I also wrote a similar script like yours internally when I initially had to update these headers. Anyways, if your script handles this case then good.

**Comment by elrond79** [comment]
The issue with the pixar licenses isn't a trailing "//", it's that they have an extra clause which you removed in most of your files.

**Comment by HamedSabri-adsk** [comment]
Then that has to be fixed too.

**Comment by elrond79** [comment]
Ok, updated!

**Pull request merged**
