### PR TITLE
Use Sdr for RfM light translation

### PR DESCRIPTION
**Pull request by dj-mcg**
Use USD's Shader Definition Registry for RfM Light Translation, which
allows us to avoid manually keeping code in sync with any associated
schemas. This change will still support the legacy method for now as
much of the Sdr capabilities are fairly recent additions to Usd.

### CODE REVIEW

**Comment by seando-adsk** [comment]
@dj-mcg There is a conflict that needs to be fixed.

**Review by ppt-adsk — APPROVED** [review]
Not my area of expertise, but LGTM.

**Comment by dj-mcg** [comment]
Ahh, I'll resolve the conflict and re-submit

**Comment by dj-mcg** [comment]
Hey @seando-adsk - I resolved the conflicts using the github tool - let me know if I managed to screw anything up in the process!

**Pull request merged**
