### PR TITLE
MAYA-110410 Author a default value for color & opacity if none are present.

### PR DESCRIPTION
**Pull request by williamkrick**

### CODE REVIEW

**Comment by HdC-adsk** [comment]
LGTM.

@kxl-adsk FYI. This fix seems to have some connection to the issue Luc and you found last week when testing a scene without authored color?

**Comment by kxl-adsk** [comment]
@HdC-adsk I don't think it will solve the problem. The solution was to author display color...but we haven't author opacity in the regression test.

**Comment by williamkrick** [comment]
@HdC-adsk does that other issue block this one? Maybe you just forgot to approve the review?

**Review by HdC-adsk — APPROVED** [review]
Not blocking. I was just waiting for Krystian to confirm.

**Pull request merged**
