### PR TITLE
Added checks for invalid UsdGeomXformOp-s before trying to use them

### PR DESCRIPTION
**Pull request by elenadBlueSky**
Added checks for invalid UsdGeomXformOp-s before trying to use them.  (There were occasionally bad ones and lack of check was causing Maya to crash.)

### CODE REVIEW

**Comment by BigRoy** [comment]
Could this be related to #95 in a way? And with the [reported Prims for the transformations that error](https://github.com/Autodesk/maya-usd/pull/103/files#diff-f7cc655c84f8c7c35ef3b34fca434539R1204) did you find a pattern to which Prims were detected to fail?

If `op.IsDefined()` returns false, can you still retrieve a name from it with `GetName()?

**Comment by elenadBlueSky** [comment]
I didn't notice a particular pattern as to which prims were detected to fail.  That doesn't mean there isn't a pattern, I just didn't notice one.  Our test case is a scene layout containing a large stadium with a number of towers.  The Maya crash I was investigating would happen when I called maya.cmds.AL_usdmaya_ProxyShapeSelect() to select one of the towers.  The person who was investigating the problem before me noticed that the towers were instanced and if she changed them to be non-instanced the crash would go away.  But we don't actually know whether the instanced/not instanced state of geometry is really related to the underlying issue or just a red herring.

Regarding GetName() on a problem op, the name obtained this way has funky characters in it.  This is what originally led me to look into the IsDefined state - I was printing out the names of the ops that were being processed in hopes of spotting where things might be failing, and the ops that failed printed some garbage characters.

**Comment by kxl-adsk** [comment]
Looking at the fix, I don't believe we have a full understanding of what is going on.
@robthebloke do you have any pointers for @elenadBlueSky on how to get to the bottom of this and hopefully catch the invalid UsdGeomXformOp earlier?

**Comment by kxl-adsk** [comment]
@elenadBlueSky I don't see any activity in this PR since November. Can it be closed?

**Comment by elenadBlueSky** [comment]
Well, we did submit this originally because it fixed a problem for us and we had wanted the fix to be integrated into the code base, provided it didn't cause problems for anyone else.  Not sure how this fell by the wayside, possibly we lost track of it while waiting for @robthebloke to comment.  I'll check with @cfmoore007 and @pilarmolinalopez to see what might have happened, but don't close this until they've had a chance to weigh in.

**Comment by pilarmolinalopez** [comment]
hi @kxl-adsk - you can close this one out. Thanks!

**Pull request closed without merging**
