### PR TITLE
[WIP] [al] re-enable testTranslators.py

### PR DESCRIPTION
**Pull request by elrond79**
This is a placeholder to remind us to get the testTranslators working (or at least confirm that they're unimportant).

### CODE REVIEW

**Comment by HamedSabri-adsk** [comment]
https://github.com/Autodesk/maya-usd/blob/cfdc288f35d0e6f1e4ba4fe536a42d8262858efc/plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py#L77

It looks like `importObject` methods are not getting called which results in some of the member variables ( e.g importObjectCount, nbImport, etc. ) values are not getting incremented.

```
FAIL: test_variantSwitch_that_removes_prim_runs_teardown (testTranslators.TestPythonTranslators)
5: ----------------------------------------------------------------------
5: Traceback (most recent call last):
5:  File "testTranslators.py", line 252, in test_variantSwitch_that_removes_prim_runs_teardown
5:   self.assertEqual(CubeGenerator.getState()["importObjectCount"],1)
5: AssertionError: 0 != 1
5: ======================================================================
5: FAIL: test_deletion_of_parent_node_by_translator_does_not_crash_Maya (testTranslators.TestPythonTranslators)
5: ----------------------------------------------------------------------
5: Traceback (most recent call last):
5:  File "testTranslators.py", line 389, in test_deletion_of_parent_node_by_translator_does_not_crash_Maya
5:   self.assertEqual(DeleteParentNodeOnPostImport.nbImport, 1)
5: AssertionError: 0 != 1
```

**Comment by kxl-adsk** [comment]
@elrond79 Please switch the destination branch to the `dev` branch. We want to delete Autodesk:autodesk/MAYA-100225/fixes_al_unit_tests since it was already merged.

**Comment by kxl-adsk** [comment]
@murphyeoin can you comment on https://github.com/Autodesk/maya-usd/pull/212#issuecomment-577406269 ?

**Comment by kxl-adsk** [comment]
@robthebloke what do you think about https://github.com/Autodesk/maya-usd/pull/212#issuecomment-577406269 ? Should we remove unused methods or there is something we are not seeing here?

**Comment by murphyeoin** [comment]
Hi @kxl-adsk sorry didn't see the original request for comment. This is working internally for us in our facility environment, I'll test it using our vanilla open source build and see what happens

**Comment by murphyeoin** [comment]
I took the latest dev branch, removed the same line as this PR removed, added an "import os" which was missing - and tests passed for me using the vanilla vfxplatform maya-2019 usd-0.19.11 build we have... Could someone else please try the same? Thanks

**Comment by HamedSabri-adsk** [comment]
Hi @murphyeoin, I just tested this PR with the latest dev branch and still get the same AssertionError.  I am actually curious to see how this test could have passed?  Can you do some debugging and tell me if importObject method is actually getting called?

https://github.com/Autodesk/maya-usd/blob/6363a2aace0bb793e26892ce69290944876f1926/plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py#L76

**Comment by murphyeoin** [comment]
Note - I've sent @HamedSabri-adsk the output of running those tests with TF_DEBUG set to "ALUSDMAYA_TRANSLATORS"

**Comment by HamedSabri-adsk** [comment]
@elrond79 @kxl-adsk 
I got a chance to look into this again this afternoon :) 
Finally some good news, I no longer can reproduce this problem at least on my MacOS and Linux ( most likely on Windows too ) with my current fix in #325.

**Comment by murphyeoin** [comment]
@HamedSabri-adsk Great news!

**Comment by murphyeoin** [comment]
I spent some time looking at this (not using your PR though, as I already had my own). Definitely the problem is related to metadata not being registered. I have added some better debugging to catch the problem early which will hopefully complement your PR

**Comment by HamedSabri-adsk** [comment]
> I spent some time looking at this (not using your PR though, as I already had my own). Tthe problem is related to the "assettype" metadata not being registered. This has been a common problem in our internal dev (i.e metadata in general not being registered)) I have added some better debugging to catch the problem early which will hopefully complement your PR

That's great. looking forward to it. Thank you @murphyeoin

**Comment by elrond79** [comment]
> @elrond79
> Please add missing `import os`.

Done

**Comment by elrond79** [comment]
Also - I'm not totally clear on what issues are still being work on, but... this was originally intended as a placeholder.  If anyone else has another more substantive PR that re-enables these tests, I'm happy to close this one.

**Pull request merged**
