### PR TITLE
apply updates based on recent core USD dev branch commits

### PR DESCRIPTION
**Pull request by mattyjams**
In particular, this PR absorbs the following core USD commits:
https://github.com/PixarAnimationStudios/USD/commit/055b8532b86f4e327fdca68536bf686d13b88ff3
https://github.com/PixarAnimationStudios/USD/commit/340759c4ef0f3c1588718acf48809e6f5dc44a57
https://github.com/PixarAnimationStudios/USD/commit/d204a531c93281f8210d53de9482a97c8fd32c50
https://github.com/PixarAnimationStudios/USD/commit/5d30f6e6ad0d12ed403dc55eaa0e75fa04d4cb92
https://github.com/PixarAnimationStudios/USD/commit/daa2d3b2e20211fe986c66f9c3d99102d5bde5f1
https://github.com/PixarAnimationStudios/USD/commit/3b0c7c90f9779f955e9751c21873b637f660cd5f
https://github.com/PixarAnimationStudios/USD/commit/287e977efd199f0c7e8f8eadd2396d85d0f27507
https://github.com/PixarAnimationStudios/USD/commit/0a8a2587db9592372ccb39deccec93f29c51084d

I updated build.md to reflect that the most recent core USD commit supported by maya-usd is the one currently on the tip of the core USD dev branch (https://github.com/PixarAnimationStudios/USD/commit/4950ffa712b7f470a45772deae9bc3b373c5714e).

This replaces #278.

### CODE REVIEW

**Comment by kxl-adsk** [comment]
@mattyjams I'm getting compilation errors when building against 20.02. Errors like
```
/git/usd/maya-usd/lib/fileio/utils/adaptor.cpp:103:45: error: no member named 'GetSchemaTypeName' in 'pxrInternal_v0_20__pxrReserved__::UsdSchemaRegistry'
    return UsdSchemaRegistry::GetInstance().GetSchemaTypeName(ty);
```

Also, I see there are newer commits in the `dev` branch (https://github.com/PixarAnimationStudios/USD/commit/40c813421425c47aa84f4572b4798fbb3430984e). Is this PR compatible with it?

**Comment by mattyjams** [comment]
Ahh, sorry about that @kxl-adsk. A bunch of schema registry changes went by and I was missing some USD version guards in one of them.

I rebased this change on the current dev and fixed that up in 518b7f8a9dd0b7ee65eda92a211f56b7d44f913e. I verified that these changes build against both the current master (20.02) and dev (https://github.com/PixarAnimationStudios/USD/commit/40c813421425c47aa84f4572b4798fbb3430984e) branches of core USD, so I also updated the build.md.

I unfortunately put the previous core USD commit SHA in the branch name, so let me know if you want a new PR with a SHA-free branch name to clean that up.

**Comment by mattyjams** [comment]
Ok, third time's the charm, hopefully...

I had missed a late-breaking change that affected the `testMayaUsdSchemasMayaReference` test, so I fixed that up in 29a3e261f75abedc1c11501eca848c5596573950. It follows the same pattern used in a somewhat similar test in usdGeom from the core USD commit https://github.com/PixarAnimationStudios/USD/commit/9994a310a3d8943abc1ee8414f6d21cfa1b39c69.

**Comment by kxl-adsk** [comment]
He he...looks to be all good now. Thank you.

**Pull request merged**
