### PR TITLE
Apply fallback value to UsdUVTexture if needed

### PR DESCRIPTION
**Pull request by fabal**
This change is to handle networks with "empty" UsdUVTexture nodes and apply any authored fallback.

### CODE REVIEW

**Review by JGamache-autodesk — CHANGES_REQUESTED** [review]
Very good, but can you provide HLSL and Cg versions as well? There is an equivalent `file.GetDimensions()` call that you could use.

**Comment by JGamache-autodesk** [comment]
After a bit of digging I found that setting the MHWRender::MSamplerStateDesc::borderColor struct member with the fallback color is probably what you are looking for. This would mean the [_GetSamplerStateDesc()](https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/render/vp2RenderDelegate/material.cpp#L637) function would need to be updated to lookup the fallback color and set it in the sampler state.

**Comment by fabal** [comment]
I went ahead with your suggestion @JGamache-autodesk , however, it doesn't give me the result I want.
My understanding is that by setting `borderColor`, changes in the shader itself are not needed anymore. Did I miss something?

**Comment by JGamache-autodesk** [comment]
I see. Works in Maya because it will generate a 1x1 texture of the fallback value when the file is not found. This can be replicated in the mayaUsdPlugin. Can you try #1692 to see if the result is what you want?

**Comment by fabal** [comment]
Closing this in favour of #1692

**Pull request closed without merging**
