### PR TITLE
MAYA-107402: A better error message when renaming a prim inside a variantset.

### PR DESCRIPTION
**Pull request by HamedSabri-adsk**
A better error message when renaming a prim inside a variantset.

### CODE REVIEW

**Review by ppt-adsk — COMMENTED** [review]
Do we have a test for this?  I searched for variant in test/lib/ufe, but only found context ops testing...

**Comment by HamedSabri-adsk** [comment]
> 
> 
> Do we have a test for this? I searched for variant in test/lib/ufe, but only found context ops testing...

No I don't have a test case for it.  I will add one to the testRename.py if it is needed.

**Comment by ppt-adsk** [comment]
> 
> 
> > Do we have a test for this? I searched for variant in test/lib/ufe, but only found context ops testing...
> 
> No I don't have a test case for it. I will add one to the testRename.py if it is needed.

Yeah, would be nice.

**Review by ppt-adsk — APPROVED** [review]
Thanks for the test!

**Pull request merged**
