### PR TITLE
Configure resolver to generate resolver context

### PR DESCRIPTION
**Pull request by kxl-adsk**
Address issue reported by https://github.com/Autodesk/maya-usd/discussions/1236. FWIW. We are still planning on exploring Ar 2.0 so things may change here.

### CODE REVIEW

**Comment by kxl-adsk** [comment]
@dj-mcg @fabal @pmolodo Please review and raise concerns.

**Comment by dolivares-spinvfx** [comment]
Might this be another relevant location?

https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/utils/utilFileSystem.cpp#L57

**Review by dj-mcg — APPROVED** [review]
Looks good, thanks!

**Review by fabal — APPROVED** [review]
That's a good thing to have :+1: 

Did you consider using `ResolverContext` objects too?
Typically in places like [this](https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/nodes/proxyShapeBase.cpp#L688) where a call like `ArGetResolver().CreateDefaultContextForAsset(fileString)` has become the default standard in many places (usdview, solaris).

A step further would be to be able to apply arbitrary resolver contexts to proxyShapes.

**Comment by kxl-adsk** [comment]
@fabal Thanks for bringing this up. I'm catching up on docs around this, it's unclear to me why we need this extra `ArGetResolver().CreateDefaultContextForAsset(fileString)` . A call to ConfigureResolverForAsset will update the [default context](https://github.com/PixarAnimationStudios/USD/blob/dc710925675f7f58f7a37f6c18d046a687b09271/pxr/usd/ar/defaultResolver_v1.cpp#L92). Why do we have to create it again explicitly instead of querying what was already configured?

Regardless, I updated the change to include suggestions raised in this review and matched the code to what is [here](https://github.com/PixarAnimationStudios/USD/blob/090ef0d849ced875b3b99a15e454b69148ccd8e1/pxr/usdImaging/usdviewq/__init__.py#L287).

@dolivares-spinvfx please give it a try since you raised this issue originally.

**Comment by fabal** [comment]
Admittedly, that explicit call to `CreateDefaultContextForAsset` is not needed in that particular case as `Stage::Open` does this by default but I guess it could be a good start towards explicit resolver contexts.
Over time, we steered clear of the default resolver context as it can lead to asset resolution "leaks" in complex scenarios (e.g. several proxyShapes, using dedicated resolver context). By "leaks", I don't mean a USD bug, I mean resolution overrides of one asset leaking into another one.
In relation to that, we also ended up guarding most of our calls to `Sdf::Layer::FindOrOpen` with a resolver context binder.
These comments are mainly for complex asset resolution use cases though, however I believe it is worth mentioning.

**Comment by dolivares-spinvfx** [comment]
Was just able to test this today due to a disk failure.  Seems like asset resolution is working with this change.  Thanks!

**Pull request merged**
