### PR TITLE
Update refactoring sandbox

### PR DESCRIPTION
**Pull request by HamedSabri-adsk**
* Reference assembly cleanup ( Factored out scene assembly from base readJob class )
* Run time path improvement for MacOSX and Linux
* Fix variant switching after merge of proxy shapes 
* Fix import (Import works in ADSK and PXR plugins, AL translator now loads and imports)
* Fix for building in debug
* Added top-level cmake option "CMAKE_WANT_UFE_BUILD" with default value ON. When enabled, we (quietly) try to find UFE and if available we enable it and use it for building. If not available, then don't compile UFE features.
* Linux translator plugins: Compilation and hdMaya camelCase fixes, mayaUsd_Translators and mayaUsd_Schemas Pixar PlugPlugin's load
* Complete selection highlight support for VP2RenderDelegate
* Fix build errors with Maya 2018
* Added new flags to have better control over Cmake stages in the build script.

### CODE REVIEW

**Comment by elrond79** [comment]
So, there's obviously a fair number of duplicated commits (ie, 29ac3fbd034cccb496582aa64e91d64e433bd98a vs cc2ca87e1e8ac028b70efaeca033d8b1f80ed543) introduced by this branch.

I'm guessing this is to make the external repo more similar to your internal repo, to make future pushes / merges / collaboration easier.  If so, then I'm on board - anything to make repo management go smoother in the future is a good thing... and it's soon enough in the lifetime of the repo that there isn't *too* much duplication.

**Comment by kxl-adsk** [comment]
There are still some improvements to the process we can do, so please keep bringing them up @elrond79 & thx!

**Comment by elrond79** [comment]
Do you have an internal repo with a different (and possibly non-git) history?  And are you intending to keep it that way? If so, Pixar has been juggling the whole internal-vs-external thing fairly well for a while (at least from an outsider's perspective), where the internal repo has a different history than the external (at least I'm assuming, since they have so much private special sauce), so they may have some valuable tips / insight on how to manage this.
We at Luma don't have any specific experience with this workflow (all our internal repos are essentially the same as our external ones, minus some private downstream branches), but we do have a fair amount of experience with automating git repos in general, and we'd also be happy to help in whatever way we can.

**Comment by kxl-adsk** [comment]
Yes, we do have an internal repo, but there shouldn't be any difference with the public repo. We still have to figure out proper internal CI integration, but I hope we can avoid having to deal with two different repos.
Since we are on the subject or internal vs public, I was wondering about the public repo PR merging process, especially when changes need to propagate into downstream branches. Can you comment on it?

**Comment by elrond79** [comment]
> Yes, we do have an internal repo, but there shouldn't be any difference with the public repo.
If you don't have a different internal repo, how were these duplicate commits created?  And do we still need them? No need to make the history much messier (and merges potentially much harder) if there's not a good reason for it.

As for PRs that need to be merged across, we have a few different options:

1. Every time a PR for an upstream branch is accepted, an automated process kicks off a merge, a test, and then (ideally) pushes the merge back to github
2. Same as above, except that you folks do it manually
3. You mandate that the merging should be the responsibility of the folks making the PR, and that they should submit "pre-merged" PRs:
    3a.  ...with one PR for each head
    3b. ...with a single PR at the most-downstream head, and clear notes on where any other upstream heads should be set to.
4. You mandate that the merging should be the responsibility of the folks making the PR, and that once an upstream PR is accepted, they make new merge-commit PRs for downstream branches.

They all have drawbacks:

1. Is the nicest, but obviously requires some CI setup. Also, you still have to have a policy for what happens when an auto-merge fails.  If a merge fails, we need to pick a fallback of either 2 or 4.
2.  Obviously, the main downside is this means more work / maintenance for Autodesk folks.  Plus, if it's a tricky merge conflict, the people submitting the PR will likely be better able to resolve it, due to more familiarity.
3. I like this, except that as the PRs build up, there's no way for submitters to know what order they're be merged in, so the downstream merges will often not be fast-forwards.  This will mean having to merge in a merge commit, creating ugly / unnecessary extra commits. Also may be a bit much to ask for a random contributor making a single-line commit to have to do a bunch of merges.
4. Slows down the process significantly.  Also, even well-meaning contributors may forget / not get around to doing this, meaning it turns into 2.

My vote is to aim for 1 (and fallback to 4 when auto-merges fail)... and in the meantime, we just do 2 or 4.

**Comment by kxl-adsk** [comment]
We are trying to understand the source of these duplicates. Will keep you posted.

**Pull request closed without merging**
